import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import { MSWProvider } from "@/components/msw-provider"
import { registerServerMocks } from "@/mocks/register-server"
import "./globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  // リクエストごとに（= HMR 後の最初のリクエストでも）サーバー MSW を再適用する。
  registerServerMocks()

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <MSWProvider>{children}</MSWProvider>
      </body>
    </html>
  )
}
